general =
{
    name = "Discord AirPlay";
    output_backend = "pipe";
    output_format = "S16_LE";
    output_rate = 44100;
    port = 5000;
};

pipe =
{
    name = "/tmp/airplay_pipe";
    output_rate = 44100;
    output_format = "S16_LE";
    output_channels = 2;
};
